/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  MyInputTask as MyInputTask
} from './components/my-input-task/my-input-task';

declare global {
  interface HTMLMyInputTaskElement extends MyInputTask, HTMLElement {
  }
  var HTMLMyInputTaskElement: {
    prototype: HTMLMyInputTaskElement;
    new (): HTMLMyInputTaskElement;
  };
  interface HTMLElementTagNameMap {
    "my-input-task": HTMLMyInputTaskElement;
  }
  interface ElementTagNameMap {
    "my-input-task": HTMLMyInputTaskElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-input-task": JSXElements.MyInputTaskAttributes;
    }
  }
  namespace JSXElements {
    export interface MyInputTaskAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  MyTodoList as MyTodoList
} from './components/my-todo-list/my-todo-list';

declare global {
  interface HTMLMyTodoListElement extends MyTodoList, HTMLElement {
  }
  var HTMLMyTodoListElement: {
    prototype: HTMLMyTodoListElement;
    new (): HTMLMyTodoListElement;
  };
  interface HTMLElementTagNameMap {
    "my-todo-list": HTMLMyTodoListElement;
  }
  interface ElementTagNameMap {
    "my-todo-list": HTMLMyTodoListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-todo-list": JSXElements.MyTodoListAttributes;
    }
  }
  namespace JSXElements {
    export interface MyTodoListAttributes extends HTMLAttributes {
      
    }
  }
}

